<template>
  <div v-if="show" class="modal modal-open">
    <div class="modal-box bg-neutral-900 border border-primary/30 max-w-3xl">
      <h3 class="font-bold text-lg text-white mb-4">Save Discovery</h3>
      
      <p class="text-slate-300 mb-4">
        Configure how and where to save the discovery results.
      </p>
      
      <div class="space-y-4">
        <div class="form-control">
          <label class="label">
            <span class="label-text text-slate-400">Discovery Name</span>
          </label>
          <input 
            type="text"
            v-model="customName"
            placeholder="e.g., initial-analysis, v2-encrypted, production-build"
            class="input input-bordered bg-black border-primary/30 focus:border-primary text-white"
          />
          <label class="label">
            <span class="label-text-alt text-slate-500">
              Leave empty to auto-generate: {{ autoGeneratedName }}
            </span>
          </label>
        </div>

        <div class="form-control">
          <label class="label">
            <span class="label-text text-slate-400">Package Version</span>
          </label>
          <input 
            type="text"
            v-model="version"
            placeholder="1.0.0"
            class="input input-bordered bg-black border-primary/30 focus:border-primary text-white"
          />
        </div>

        <div class="divider text-slate-600">Save Location</div>

        <PathBrowser
          v-model="savePath"
          :default-path="previewPackageId"
          label="Browse and select save location"
          api-endpoint="http://localhost:8000/api/devices/workshop/folders"
        />

        <div class="divider text-slate-600">Preview</div>

        <div class="bg-black/30 border border-primary/20 rounded-lg p-3">
          <div class="text-xs text-slate-400 mb-1">Final Save Path:</div>
          <div class="font-mono text-sm text-slate-200 break-all leading-relaxed">
            <span class="text-slate-600">local_storage/saved_discoveries/</span><span v-if="savePath" class="text-cyan-400">{{ savePath }}/</span><span class="text-green-400">{{ finalFolderName }}</span>/
          </div>
          <div class="text-xs text-slate-500 mt-2">
            Files: metadata.json, java_classes.json, native_modules.json, user_data.json
          </div>
        </div>
      </div>
      
      <div class="modal-action">
        <button 
          type="button"
          class="btn btn-ghost" 
          @click="handleClose"
          :disabled="saving"
        >
          Cancel
        </button>
        <button 
          type="button"
          class="btn btn-primary" 
          @click="handleSave"
          :disabled="saving || !version"
        >
          <span v-if="saving" class="loading loading-spinner loading-xs"></span>
          {{ saving ? 'Saving...' : 'Save Discovery' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed, watch } from 'vue'
import PathBrowser from '../../../../../components/PathBrowser.vue'

export default {
  name: 'SaveDiscoveryModal',
  components: {
    PathBrowser
  },
  props: {
    show: {
      type: Boolean,
      required: true
    },
    metadata: {
      type: Object,
      default: null
    },
    saving: {
      type: Boolean,
      default: false
    }
  },
  emits: ['close', 'save'],
  setup(props, { emit }) {
    const version = ref('1.0.0')
    const customName = ref('')
    const savePath = ref('')
    
    const previewPackageId = computed(() => {
      return props.metadata?.package_id || 'com.example.app'
    })

    const autoGeneratedName = computed(() => {
      const now = new Date()
      const dateStr = now.toISOString().split('T')[0]
      const safeVersion = version.value.replace(/[/\\]/g, '_').replace(/\s+/g, '_')
      return `${dateStr}_${safeVersion}`
    })
    
    const finalFolderName = computed(() => {
      if (customName.value.trim()) {
        return customName.value.trim().replace(/\s+/g, '_')
      }
      return autoGeneratedName.value
    })
    
    watch(() => props.show, (newShow) => {
      if (newShow) {
        if (props.metadata?.package_version) {
          version.value = props.metadata.package_version
        }
        customName.value = ''
        savePath.value = previewPackageId.value
      }
    })
    
    const handleClose = () => {
      emit('close')
    }
    
    const handleSave = () => {
      emit('save', {
        version: version.value,
        customName: customName.value.trim() || null,
        savePath: savePath.value.trim() || null
      })
    }
    
    return {
      version,
      customName,
      savePath,
      previewPackageId,
      autoGeneratedName,
      finalFolderName,
      handleClose,
      handleSave
    }
  }
}
</script>

